# Generated by Django 2.2 on 2021-04-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='permiso',
        ),
    ]
