# Generated by Django 2.2 on 2021-04-13 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0002_remove_puesto_empleado'),
        ('empleados', '0002_remove_empleado_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='puestos.Puesto'),
        ),
    ]
