# Generated by Django 2.2 on 2021-04-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='empleado',
        ),
    ]
